
server:  port: 8081 
---
spring:
  resources:
    static-locations: "file:../app"
---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:../sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never